[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "verihire-se"
version = "0.0.1"
authors = [
  { name = "Nidhish", email = "nnidhish_be24@thapar.edu" },
]
description = "VeriHire - AI-Based Resume Screening and Candidate Evaluation System"
readme = "README.md"
requires-python = ">=3.8"

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
]

dependencies = ["click"]

[project.urls]
Homepage = "https://github.com/nidhish2211/VeriHire_SE"
Issues = "https://github.com/nidhish2211/VeriHire_SE/issues"

[tool.pytest.ini_options]
pythonpath = [
  "code"
]